-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 23:47:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lendingLibrary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lendingLibrary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lendingLibrary` ;
USE `lendingLibrary` ;

-- -----------------------------------------------------
-- Table `lendingLibrary`.`Contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lendingLibrary`.`Contacts` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `company` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `jobTitle` VARCHAR(45) NULL,
  `businessphone` INT NULL,
  `homePhone` INT NULL,
  `mobilePhone` INT NULL,
  `faxNumber` INT NULL,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `postalCode` INT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lendingLibrary`.`Assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lendingLibrary`.`Assets` (
  `itemID` INT NOT NULL,
  `Contacts_ID` INT NOT NULL,
  `item` VARCHAR(45) NULL,
  `manufacturer` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `acquiredDate` DATE NULL,
  `purchasePrice` INT NULL,
  `currentValue` INT NULL,
  `itemCondition` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `comments` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`itemID`),
  INDEX `fk_Assets_Contacts_idx` (`Contacts_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Assets_Contacts`
    FOREIGN KEY (`Contacts_ID`)
    REFERENCES `lendingLibrary`.`Contacts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lendingLibrary`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lendingLibrary`.`Transactions` (
  `Assets_itemID` INT NOT NULL,
  `Contacts_ID` INT NOT NULL,
  `checkOutCondition` VARCHAR(45) NULL,
  `checkOutNotes` VARCHAR(45) NULL,
  `checkInDate` DATE NULL,
  `checkInCondition` VARCHAR(45) NULL,
  `checkInNotes` VARCHAR(45) NULL,
  `dueDate` DATE NULL,
  `checkOutDate` DATE NULL,
  INDEX `fk_Transactions_Assets1_idx` (`Assets_itemID` ASC) VISIBLE,
  INDEX `fk_Transactions_Contacts1_idx` (`Contacts_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions_Assets1`
    FOREIGN KEY (`Assets_itemID`)
    REFERENCES `lendingLibrary`.`Assets` (`itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Contacts1`
    FOREIGN KEY (`Contacts_ID`)
    REFERENCES `lendingLibrary`.`Contacts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
